version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgresql_rust
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rust_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rust_network

volumes:
  postgres_data:

networks:
  rust_network:
    driver: bridge
